### ISSUE TITLE
Add toolkit version check

### ISSUE THREAD

**Issue by markheger** [IBMStreams/pypi.streamsx.inet#11]
```
     [echo] ..streamsx.inet.tests.test_inet/test_request_get_url_in_input_stream.spl:20:7: CDISP0054E ERROR: The extraHeaderAttribute parameter is unknown and was not defined for the HTTPRequest operator.
     [echo] SEVERE:
     [echo] CDISP0092E ERROR: Because of previous compilation errors, the compile process cannot continue.
     [echo] Exception in thread "main" java.lang.Exception: CDIST3417E: SPL compilation failed!
     [echo] at com.ibm.streamsx.topology.internal.streams.InvokeSc.invoke(InvokeSc.java:158)
     [echo] at com.ibm.streamsx.topology.internal.context.streams.BundleStreamsContext.doSPLCompile(BundleStreamsContext.java:143)
     [echo] at com.ibm.streamsx.topology.internal.context.streams.BundleStreamsContext.action(BundleStreamsContext.java:101)
     [echo] at com.ibm.streamsx.topology.internal.context.JSONStreamsContext._submit(JSONStreamsContext.java:89)
     [echo] at com.ibm.streamsx.topology.internal.context.streams.BundleStreamsContext._submit(BundleStreamsContext.java:63)
     [echo] at com.ibm.streamsx.topology.internal.context.streams.BundleUserStreamsContext.action(BundleUserStreamsContext.java:39)
     [echo] at com.ibm.streamsx.topology.internal.context.JSONStreamsContext._submit(JSONStreamsContext.java:89)
     [echo] at com.ibm.streamsx.topology.internal.context.JSONStreamsContext.submit(JSONStreamsContext.java:108)
     [echo] at com.ibm.streamsx.topology.context.local.StreamsContextSubmit.main(StreamsContextSubmit.java:35)
     [echo] F....
     [echo] ======================================================================
     [echo] FAIL: test_request_get_url_in_input_stream (streamsx.inet.tests.test_inet.TestHTTP)

```

**Comment by markheger** [comment]
add_toolkit_dependency because `extraHeaderAttribute` parameter has been introduced in v3.0
